In [103]:
import requests
import zipfile
import io
import pandas as pd

# Definir URLs
dataRepo1 = pd.read_excel('https://github.com/Camilo0702/PC3-Bernabe/raw/refs/heads/main/level1.xlsx')
dataRepo2 = pd.read_excel('https://github.com/Camilo0702/PC3-Bernabe/raw/refs/heads/main/level2.xlsx')
dataRepo3 = pd.read_excel('https://github.com/Camilo0702/PC3-Bernabe/raw/refs/heads/main/level3.xlsx')
dataRepo4 = pd.read_excel('https://github.com/Camilo0702/PC3-Bernabe/raw/refs/heads/main/level4.xlsx')
countryCodesURL = 'https://github.com/Camilo0702/PC3-Bernabe/raw/main/countryCODES.xlsx'
fallecidosURL = 'https://github.com/Camilo0702/PC3-Bernabe/raw/main/fallecidosCOVID.csv'

In [104]:
dataRepo1.head()

,Unnamed: 0,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank,NaN
4,NaN,NaN,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN,NaN

In [105]:
dataRepo1 = dataRepo1[3:].reset_index(drop=True)  # Eliminar filas y reiniciar el índice
# Usar la cuarta fila (ahora la primera) como encabezado
new_header = dataRepo1.iloc[0]  # Tomar la nueva cabecera de la primera fila
dataRepo1 = dataRepo1[1:]  # Eliminar la fila que se convirtió en encabezado
dataRepo1.columns = new_header  # Asignar la nueva cabecera
dataRepo1 = dataRepo1[2:].reset_index(drop=True)  # Eliminar filas y reiniciar el índice
dataRepo1.head()  # Mostrar las primeras filas del DataFrame modificado

,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank,NaN
0,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3,VERY HIGH HUMAN DEVELOPMENT
1,2,Norway,0.961,NaN,83.2339,NaN,18.1852,c,13.00363,NaN,64660.10622,NaN,6,NaN,1,VERY HIGH HUMAN DEVELOPMENT
2,3,Iceland,0.959,NaN,82.6782,NaN,19.163059,c,13.76717,NaN,55782.04981,NaN,11,NaN,2,VERY HIGH HUMAN DEVELOPMENT
3,4,"Hong Kong, China (SAR)",0.952,NaN,85.4734,d,17.27817,NaN,12.22621,NaN,62606.8454,NaN,6,NaN,4,VERY HIGH HUMAN DEVELOPMENT
4,5,Australia,0.951,NaN,84.5265,NaN,21.05459,c,12.72682,NaN,49238.43335,NaN,18,NaN,5,VERY HIGH HUMAN DEVELOPMENT

In [106]:
# Eliminar columnas por índice
dataRepo1 = dataRepo1.drop(dataRepo1.columns[[0, 3, 5, 7, 9, 11, 13, 14]], axis=1)

dataRepo1.head()

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18

In [107]:
dataRepo2 = dataRepo2[2:].reset_index(drop=True)  # Eliminar filas y reiniciar el índice
new_header = dataRepo2.iloc[0]  # Tomar la nueva cabecera de la primera fila
dataRepo2 = dataRepo2[0:]  # Eliminar la fila que se convirtió en encabezado
dataRepo2 = dataRepo2.drop(dataRepo2.columns[[0, 6, 8, 10, 11]], axis=1)
dataRepo2.head()  # Mostrar las primeras filas del DataFrame modificado

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,Albania,0.796,76.4626,14.448000,11.286455,14131.11039,17.0
1,Bulgaria,0.795,71.7980,13.897290,11.413180,23078.95595,-8.0
2,Grenada,0.795,74.9362,18.662020,9.032104,13483.57740,18.0
3,Barbados,0.790,77.5714,15.713385,9.852701,12306.34100,26.0
4,Antigua and Barbuda,0.788,78.4968,14.184626,9.293741,16792.36595,2.0

In [108]:
dataRepo3 = dataRepo3[2:].reset_index(drop=True)  # Eliminar filas y reiniciar el índice
new_header = dataRepo3.iloc[0]  # Tomar la nueva cabecera de la primera fila
dataRepo3 = dataRepo3[0:]  # Eliminar la fila que se convirtió en encabezado
dataRepo3 = dataRepo3.drop(dataRepo3.columns[[0, 3, 5, 7, 9, 11, 13, 14]], axis=1)
dataRepo3.head()  # Mostrar las primeras filas del DataFrame modificado

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,Philippines,0.699,69.2664,13.126570,8.969100,8920.428468,-3.0
1,Botswana,0.693,61.1409,12.265138,10.340000,16198.318410,-43.0
2,Bolivia (Plurinational State of),0.692,63.6304,14.946971,9.827750,8111.190194,0.0
3,Kyrgyzstan,0.692,69.9774,13.195300,11.374106,4566.303831,26.0
4,Venezuela (Bolivarian Republic of),0.691,70.5536,12.816080,11.107277,4810.882621,20.0

In [110]:
new_header = dataRepo4.iloc[0]  # Tomar la nueva cabecera de la primera fila
dataRepo4 = dataRepo4[0:]  # Eliminar la fila que se convirtió en encabezado
dataRepo4 = dataRepo4.drop(dataRepo4.columns[[0, 2, 9]], axis=1)
dataRepo4.head()  # Mostrar las primeras filas del DataFrame modificado

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,Tanzania (United Republic of),0.549,66.2007,9.221490,6.372899,2664.329096,7
1,Pakistan,0.544,66.0979,8.658350,4.536330,4623.705430,-19
2,Togo,0.539,61.6194,12.950494,5.016807,2166.619062,12
3,Haiti,0.535,63.1924,9.700000,5.554000,2847.500746,2
4,Nigeria,0.535,52.6760,10.127584,7.181074,4790.284425,-22

In [111]:
dataframes = [dataRepo1, dataRepo2, dataRepo3, dataRepo4]

# Concatenar los DataFrames, ignorando el encabezado duplicado
combined_data = pd.concat(dataframes, ignore_index=True)

# Mostrar las primeras filas del DataFrame combinado
combined_data.head()

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18

In [127]:
combined_data

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18
...,...,...,...,...,...,...,...
186,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4
187,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611,1
188,Niger,0.4,61.5763,6.957112,2.116717,1239.866936,-3
189,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7
190,South Sudan,0.385,54.9752,5.54251,5.72614,767.787,-1

In [128]:
combined_data.to_csv("combined_data.csv", index=False)
print("El archivo combined_data.csv ha sido guardado correctamente.")

El archivo combined_data.csv ha sido guardado correctamente.

In [112]:
country_codes = pd.read_excel(countryCodesURL)

# Ver las primeras filas del DataFrame de country codes para saber qué columnas tiene
country_codes.head()

,Country,Officialstatename,InternetccTLD,iso2,iso3
0,AFGHANISTAN,The Islamic Republic of Afghanistan,.af,AF,AFG
1,ALBANIA,The Republic of Albania,.al,AL,ALB
2,ALGERIA,The People's Democratic Republic of Algeria,.dz,DZ,DZA
3,ANGOLA,The Republic of Angola,.ao,AO,AGO
4,ANTIGUA AND BARBUDA,Antigua and Barbuda,.ag,AG,ATG

In [113]:
# Supongamos que quieres hacer el merge usando una columna llamada 'Country' en combined_data
# y 'CountryCode' en country_codes. Puedes cambiar los nombres según sea necesario.

# Realizar el merge
merged_data = pd.merge(combined_data, country_codes, left_on='Country', right_on='Country', how='left')

# Mostrar las primeras filas del DataFrame combinado
merged_data.head()

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,Officialstatename,InternetccTLD,iso2,iso3
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,NaN,NaN,NaN,NaN
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,NaN,NaN,NaN,NaN
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11,NaN,NaN,NaN,NaN
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6,NaN,NaN,NaN,NaN
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18,NaN,NaN,NaN,NaN

In [114]:
merged_data = merged_data.drop(merged_data.columns[[7, 8, 9, 10]], axis=1)
merged_data.head()

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18

In [126]:
merged_data

,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5
1,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6
2,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11
3,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6
4,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18
...,...,...,...,...,...,...,...
186,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4
187,Central African Republic,0.404,53.8947,8.040172,4.334,966.058611,1
188,Niger,0.4,61.5763,6.957112,2.116717,1239.866936,-3
189,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7
190,South Sudan,0.385,54.9752,5.54251,5.72614,767.787,-1

In [129]:
merged_data.to_csv("merged_data.csv", index=False)
print("El archivo merged_data.csv ha sido guardado correctamente.")

El archivo merged_data.csv ha sido guardado correctamente.

In [123]:
fallecidos_data = pd.read_csv(fallecidosURL, sep=';')
fallecidos_data.head()

,FECHA_CORTE,FECHA_FALLECIMIENTO,EDAD_DECLARADA,SEXO,CLASIFICACION_DEF,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,UUID
0,20240317,20220219,63,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101.0,203506.0
1,20240317,20210529,74,MASCULINO,Criterio virológico,TUMBES,TUMBES,TUMBES,240101.0,203532.0
2,20240317,20210623,72,FEMENINO,Criterio SINADEF,TACNA,TACNA,ALTO DE LA ALIANZA,230102.0,203584.0
3,20240317,20210824,85,MASCULINO,Criterio investigación Epidemiológica,TUMBES,TUMBES,TUMBES,240101.0,212541.0
4,20240317,20210627,46,MASCULINO,Criterio virológico,TACNA,TACNA,ALTO DE LA ALIANZA,230102.0,203665.0

In [124]:
# Convertir la columna 'FECHA_FALLECIMIENTO' a tipo datetime
fallecidos_data['FECHA_FALLECIMIENTO'] = pd.to_datetime(fallecidos_data['FECHA_FALLECIMIENTO'], format='%Y%m%d')

# Agrupar por mes y año y contar el total de fallecidos
# Suponiendo que cada fila representa un fallecido, contaremos las filas por cada mes
reporte_mensual = fallecidos_data.groupby(fallecidos_data['FECHA_FALLECIMIENTO'].dt.to_period('M')).size().reset_index(name='Total_Fallecidos')

# Renombrar la columna del período a un formato más comprensible
reporte_mensual['Mes_Año'] = reporte_mensual['FECHA_FALLECIMIENTO'].dt.strftime('%Y-%m')
reporte_mensual = reporte_mensual[['Mes_Año', 'Total_Fallecidos']]  # Reorganizar columnas

# Mostrar el DataFrame resultante
reporte_mensual

    Mes_Año  Total_Fallecidos
0   2020-03               181
1   2020-04              5134
2   2020-05             16363
3   2020-06             17462
4   2020-07             18501
5   2020-08             17668
6   2020-09              8437
7   2020-10              4471
8   2020-11              3229
9   2020-12              3885
10  2021-01             11175
11  2021-02             18645
12  2021-03             20691
13  2021-04             23110
14  2021-05             16692
15  2021-06              7722
16  2021-07              3481
17  2021-08              1850
18  2021-09              1140
19  2021-10              1066
20  2021-11              1107
21  2021-12              1283
22  2022-01              3562
23  2022-02              3503
24  2022-03              1299
25  2022-04               741
26  2022-05               625
27  2022-06               542
28  2022-07              1025
29  2022-08              1429
30  2022-09               892
31  2022-10               429
32  2022-11               272
33  2022-12               423
34  2023-01               371
35  2023-02               287
36  2023-03               295
37  2023-04               337
38  2023-05               323
39  2023-06               291
40  2023-07               258
41  2023-08               249
42  2023-09                60
43  2023-10                26
44  2023-11                33
45  2023-12                40
46  2024-01               249
47  2024-02                62
48  2024-03                 2

In [130]:
reporte_mensual.to_csv("reporte_mensual.csv", index=False)
print("El archivo reporte_mensual.csv ha sido guardado correctamente.")

El archivo reporte_mensual.csv ha sido guardado correctamente.

In [125]:
fallecidos_data['FECHA_FALLECIMIENTO'] = pd.to_datetime(fallecidos_data['FECHA_FALLECIMIENTO'], format='%Y%m%d')

# Agrupar por mes y clasificar por tipo de muerte (suponiendo que el tipo de muerte está en 'CLASIFICACION_DEF')
reporte_mensual_tipo = fallecidos_data.pivot_table(
    index=fallecidos_data['FECHA_FALLECIMIENTO'].dt.to_period('M'),  # Agrupar por mes
    columns='CLASIFICACION_DEF',  # Usar el tipo de muerte como columnas
    aggfunc='size',  # Contar la cantidad de ocurrencias
    fill_value=0  # Rellenar con 0 en caso de que no haya datos para ese tipo
).reset_index()

# Renombrar la columna del período a un formato más comprensible
reporte_mensual_tipo['Mes_Año'] = reporte_mensual_tipo['FECHA_FALLECIMIENTO'].dt.strftime('%Y-%m')
reporte_mensual_tipo = reporte_mensual_tipo.drop(columns=['FECHA_FALLECIMIENTO'])  # Eliminar la columna original del periodo

# Mostrar el DataFrame resultante
reporte_mensual_tipo

CLASIFICACION_DEF,Criterio SINADEF,Criterio clínico,Criterio investigación Epidemiológica,Criterio nexo epidemiológico,Criterio radiológico,Criterio serológico,Criterio virológico,NotiCovid,sinadef,Mes_Año
0,35,52,25,2,7,2,58,0,0,2020-03
1,1793,541,498,68,182,778,1274,0,0,2020-04
2,6826,1152,1427,203,480,3233,3042,0,0,2020-05
3,5722,670,1706,251,391,5605,3117,0,0,2020-06
4,5012,609,1512,262,415,7501,3190,0,0,2020-07
5,4589,611,1456,208,534,7400,2870,0,0,2020-08
6,1984,475,755,105,233,3483,1402,0,0,2020-09
7,1091,463,469,50,172,1417,809,0,0,2020-10
8,704,462,307,37,186,867,666,0,0,2020-11
9,802,547,171,41,179,1047,1098,0,0,2020-12
10,2190,514,323,107,434,2448,5159,0,0,2021-01
11,4993,501,465,150,556,2539,9441,0,0,2021-02
12,6100,525,517,229,456,1703,11161,0,0,2021-03
13,7450,748,591,246,363,1488,12224,0,0,2021-04
14,5225,628,349,155,283,1175,8877,0,0,2021-05
15,2723,116,123,51,138,746,3825,0,0,2021-06
16,1025,113,67,35,68,521,1652,0,0,2021-07
17,578,75,22,15,36,287,837,0,0,2021-08
18,554,12,0,0,0,190,384,0,0,2021-09
19,469,12,0,0,0,148,437,0,0,2021-10
20,441,16,0,0,0,157,493,0,0,2021-11
21,585,8,0,0,0,133,557,0,0,2021-12
22,1894,22,0,0,0,41,1605,0,0,2022-01
23,1604,20,0,0,0,1,1878,0,0,2022-02
24,352,6,0,0,0,0,941,0,0,2022-03
25,131,9,0,0,0,0,601,0,0,2022-04
26,85,3,0,0,0,0,537,0,0,2022-05
27,81,3,0,0,0,0,458,0,0,2022-06
28,299,3,0,0,0,0,723,0,0,2022-07
29,405,6,0,0,0,0,1018,0,0,2022-08
30,154,12,0,0,0,0,726,0,0,2022-09
31,53,59,0,0,0,0,317,0,0,2022-10
32,23,0,0,0,0,0,249,0,0,2022-11
33,66,0,0,0,0,0,357,0,0,2022-12
34,34,1,0,0,0,0,336,0,0,2023-01
35,4,0,0,0,0,0,283,0,0,2023-02
36,6,0,0,0,0,0,289,0,0,2023-03
37,17,0,0,0,0,0,320,0,0,2023-04
38,6,0,0,0,0,0,317,0,0,2023-05
39,2,0,0,0,0,0,289,0,0,2023-06
40,3,0,0,0,0,0,255,0,0,2023-07
41,7,0,0,0,0,0,242,0,0,2023-08
42,7,0,0,0,0,0,53,0,0,2023-09
43,8,0,0,0,0,0,18,0,0,2023-10
44,13,0,0,0,0,0,20,0,0,2023-11
45,17,0,0,0,0,0,22,1,0,2023-12
46,35,0,0,0,0,0,83,115,16,2024-01
47,1,0,0,0,0,0,45,16,0,2024-02
48,0,0,0,0,0,0,2,0,0,2024-03

In [131]:
reporte_mensual_tipo.to_csv("reporte_mensual_tipo.csv", index=False)
print("El archivo reporte_mensual_tipo.csv ha sido guardado correctamente.")

El archivo reporte_mensual_tipo.csv ha sido guardado correctamente.